# Generated by Django 2.1 on 2019-02-06 18:59

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import system.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarjetNauta', models.CharField(default='', max_length=30, verbose_name='Tarjeta Nauta')),
                ('creationDate', models.DateField(auto_now_add=True, verbose_name='Fecha de la Donacion')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL, verbose_name='Donante')),
            ],
            options={
                'verbose_name': 'Donacion',
                'verbose_name_plural': 'Donaciones',
            },
        ),
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=120, verbose_name='Título')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='Contenido')),
                ('creationDate', models.DateField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('wroteBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wroteBy', to=settings.AUTH_USER_MODEL, verbose_name='Escritor')),
            ],
            options={
                'verbose_name': 'Reporte de Error',
                'verbose_name_plural': 'Reportes de Errores',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=120, verbose_name='Título')),
                ('description', models.CharField(default='', max_length=200, validators=[system.validators.validate], verbose_name='Descripcion')),
                ('image', models.ImageField(upload_to='', verbose_name='Imagen Representativa')),
                ('creationDate', models.DateField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('show_anticheat', models.BooleanField(default=False, verbose_name='Mostrar en el AntiParche')),
                ('wroteBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_wroteBy', to=settings.AUTH_USER_MODEL, verbose_name='Escritor')),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('maxJoin', models.IntegerField(default=0, verbose_name='Maximos Dentro')),
            ],
        ),
        migrations.CreateModel(
            name='TemplatesStatics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=240, verbose_name='Título')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='Contenido')),
                ('type', models.BooleanField(default='enlace', verbose_name='Nombre del enlace')),
            ],
            options={
                'verbose_name': 'Plantilla Estática',
                'verbose_name_plural': 'Plantillas Estáticas',
            },
        ),
    ]
