# Generated by Django 2.1.5 on 2019-02-10 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donations',
            old_name='tarjetNauta',
            new_name='targetNauta',
        ),
    ]
