# Generated by Django 2.1.5 on 2019-03-17 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donations',
            name='accepted',
        ),
    ]
