# Generated by Django 2.1.5 on 2019-02-11 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20190210_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='news', verbose_name='Imagen Representativa'),
        ),
    ]
