# Generated by Django 2.1.5 on 2019-02-11 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20190211_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='donations',
            name='accepted',
            field=models.BooleanField(default=False, verbose_name='Donacion Aceptada'),
        ),
    ]
