# Generated by Django 2.1.5 on 2019-03-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AntiCheat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default='1.0.0', max_length=20, verbose_name='Version del AntiParches')),
                ('show_anticheat', models.BooleanField(default=False, verbose_name='Mostrar en el AntiParche')),
                ('launcher', models.FileField(upload_to='', verbose_name='Launcher LEVERAGE')),
            ],
            options={
                'verbose_name': 'AntiParche',
                'verbose_name_plural': 'AntiParches',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Fecha')),
                ('action', models.CharField(default='Join MacKey from the Server', max_length=300, verbose_name='Accion')),
            ],
            options={
                'verbose_name': 'Registro',
                'verbose_name_plural': 'Registros',
            },
        ),
        migrations.CreateModel(
            name='Mods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre del Archivo')),
                ('hash', models.CharField(max_length=80, verbose_name='Hash')),
            ],
            options={
                'verbose_name': 'Mod del Juego',
                'verbose_name_plural': 'Mods del Juego',
            },
        ),
        migrations.CreateModel(
            name='ResourcePack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre del Archivo')),
                ('hash', models.CharField(max_length=80, verbose_name='Hash')),
            ],
            options={
                'verbose_name': 'Paquete de Recurso',
                'verbose_name_plural': 'Paquetes de Recursos',
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vertionType', models.CharField(default='RELEASE', max_length=20, verbose_name='Tipo de Version')),
                ('hash', models.CharField(max_length=80, verbose_name='Hash')),
                ('versionId', models.CharField(default='forge1.12.2-14.23.5.2768', max_length=120, verbose_name='Version de Forge')),
                ('version', models.CharField(default='1.12.2', max_length=20, verbose_name='Version de Minecraft')),
            ],
            options={
                'verbose_name': 'Version del Juego',
                'verbose_name_plural': 'Versiones del Juego',
            },
        ),
    ]
