# Generated by Django 2.1.5 on 2019-02-14 04:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anticheat',
            name='launcher',
            field=models.FileField(default=django.utils.timezone.now, upload_to='', verbose_name='Launcher LEVERAGE'),
            preserve_default=False,
        ),
    ]
