# Generated by Django 2.1.5 on 2019-02-24 01:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_mods_namejar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mods',
            name='modId',
        ),
        migrations.RemoveField(
            model_name='mods',
            name='nameJar',
        ),
        migrations.RemoveField(
            model_name='mods',
            name='space',
        ),
        migrations.RemoveField(
            model_name='mods',
            name='version',
        ),
        migrations.RemoveField(
            model_name='mods',
            name='vmc',
        ),
        migrations.RemoveField(
            model_name='resourcepack',
            name='space',
        ),
        migrations.RemoveField(
            model_name='version',
            name='space',
        ),
        migrations.AddField(
            model_name='mods',
            name='hash',
            field=models.CharField(default=django.utils.timezone.now, max_length=80, verbose_name='Hash'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resourcepack',
            name='hash',
            field=models.CharField(default=django.utils.timezone.now, max_length=80, verbose_name='Hash'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='version',
            name='hash',
            field=models.CharField(default=django.utils.timezone.now, max_length=80, verbose_name='Hash'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mods',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Nombre del Archivo'),
        ),
        migrations.AlterField(
            model_name='resourcepack',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Nombre del Archivo'),
        ),
    ]
