# Generated by Django 2.1.5 on 2019-02-11 22:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_remove_profile_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='uuid',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='UUID'),
            preserve_default=False,
        ),
    ]
