# Generated by Django 2.1.5 on 2019-02-13 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0003_profile_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ban',
            name='user_ban',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ban', to=settings.AUTH_USER_MODEL, unique=True, verbose_name='Usuario Baneado'),
        ),
    ]
