# Generated by Django 2.1.5 on 2019-02-13 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0004_auto_20190213_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ban',
            name='user_ban',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_ban', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Baneado'),
        ),
    ]
